export default {
    overview: "组件总览",
    "--- 基础交互": {
        type: "separator",
        title: "基础交互",
    },
    button: "按钮 Button",
    input: "输入框 Input",
    "--- 布局容器": {
        type: "separator",
        title: "布局容器",
    },
    panel: "面板 Panel",
    card: "卡片 Card",
    divider: "分隔线 Divider",
    "container-slot": "容器槽 ContainerSlot",
    "--- 布局 L": {
        type: "separator",
        title: "布局 L",
    },
    stack: "堆叠 Stack",
    grid: "网格 Grid",
    "scroll-view": "滚动视图 ScrollView",
    section: "分组 Section",
    spacer: "弹性间距 Spacer",
    "--- 组合 B": {
        type: "separator",
        title: "组合 B",
    },
    modal: "弹窗 Modal",
    menu: "菜单 Menu",
    "scrolling-list": "滚动列表 ScrollingList",
    dropdown: "下拉 Dropdown",
    form: "表单 Form",
    "navigation-bar": "顶栏 NavigationBar",
    toast: "通知 Toast",
    "search-field": "搜索框 SearchField",
    toggle: "开关 Toggle",
    "--- 数据展示": {
        type: "separator",
        title: "数据展示",
    },
    text: "文本 Text",
    "list-item": "列表项 ListItem",
    "key-icon": "按键图标 KeyIcon",
    bubble: "气泡 Bubble",
    "--- 导航 N": {
        type: "separator",
        title: "导航 N",
    },
    "tab-bar": "标签栏 TabBar",
    "filter-bar": "筛选栏 FilterBar",
    breadcrumb: "面包屑 Breadcrumb",
    pager: "分页 Pager",
    "--- 交互 I": {
        type: "separator",
        title: "交互 I",
    },
    "text-area": "多行输入 TextArea",
    slider: "滑条 Slider",
    stepper: "加减器 Stepper",
    picker: "选择器 Picker",
    "--- 数据 D": {
        type: "separator",
        title: "数据 D",
    },
    icon: "图标 Icon",
    image: "图片 Image",
    badge: "徽标 Badge",
    "--- 反馈": {
        type: "separator",
        title: "反馈",
    },
    tooltip: "提示框 Tooltip",
    progress: "进度条 Progress",
    "--- 主题": {
        type: "separator",
        title: "主题",
    },
    theme: "主题令牌 Theme",
};